# Generated by Django 5.2.1 on 2025-06-08 00:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва компанії')),
            ],
            options={
                'db_table': 'company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва країни')),
            ],
            options={
                'db_table': 'country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва жанру')),
            ],
            options={
                'db_table': 'genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID з CSV')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('poster_path', models.URLField(blank=True, max_length=500, null=True, verbose_name='Шлях до постеру')),
                ('overview', models.TextField(blank=True, verbose_name='Опис')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата виходу')),
                ('runtime', models.PositiveIntegerField(blank=True, null=True, verbose_name='Тривалість (хв)')),
                ('vote_average', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Середній рейтинг')),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість голосів')),
                ('popularity', models.FloatField(blank=True, null=True, verbose_name='Популярність')),
                ('companies', models.ManyToManyField(blank=True, related_name='movies', to='reelchoice_app.company', verbose_name='Компанії виробництва')),
                ('countries', models.ManyToManyField(blank=True, related_name='movies', to='reelchoice_app.country', verbose_name='Країни виробництва')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='reelchoice_app.genre', verbose_name='Жанри')),
            ],
            options={
                'db_table': 'movie',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст коментаря')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reelchoice_app.movie')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['user', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оцінка')),
                ('content', models.TextField(verbose_name='Текст коментаря')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='reelchoice_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating',
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
