# Generated by Django 5.2.1 on 2025-06-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reelchoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content',
        ),
    ]
