# Generated by Django 5.2.1 on 2025-06-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reelchoice_app', '0002_remove_rating_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='popularity',
        ),
    ]
