# Generated by Django 5.2.3 on 2025-06-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelchoice_app', '0003_remove_movie_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug жанру'),
        ),
    ]
